services:
    redis:
        image: redis:7-alpine
        container_name: redis_container
        ports: 
            - '6379:6379'
        volumes: 
            - spotify_data:/data:rw
        restart: on-failure:2
        command: redis-server --appendonly yes

volumes:
    spotify_data:
